"""initial migration

Revision ID: 45e948bc8f69
Revises: None
Create Date: 2014-06-29 04:18:50.537000

"""

# revision identifiers, used by Alembic.
revision = '45e948bc8f69'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
